version: '3'

services:
    nodejs-app:
        build:
          context: ./JS/
        container_name: nodejsserver
        hostname: nodejsserver
        ports:
            - "3000:3000" 
        networks:
            - example-net  
    nginx:
        build:
          context: ./Nginx/
        container_name: nginx
        hostname: nginx
        ports:
            - "8000:80" 
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
    external: true